# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - habilitar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ddb0afe0a443434b8721ee1fe8422916 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69f552a6a1ce4ca7a2d153a2b5b8b84a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ddb0afe0a443434b8721ee1fe8422916 }}/jeffersonneto/habilitar-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'habilitar'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_83651fb007ee48fea1bf856771065f06 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ddb0afe0a443434b8721ee1fe8422916 }}/jeffersonneto/habilitar-frontend:${{ github.sha }}'